Remove placeholder tests
sshnet/SSH.NET pull request #1183
Opened 2023-09-23 15:57 UTC by Rob-Hague

These have no value and make it harder to trace references with intellisense. Removing them also helps narrow down the tests we need to address

Before:

![image](https://github.com/sshnet/SSH.NET/assets/5132141/076eeda7-8c20-4765-808e-66d47e5d5527)

After:

![image](https://github.com/sshnet/SSH.NET/assets/5132141/b04fad47-571a-4e59-82e7-a482b4629aec)

(the 3 extra passing tests is `ExtensionsTest_Reverse.Null` for each tfm and the 2 failing tests are #1166)

2023-10-12 07:34 UTC, WojciechNagorski commented
@drieseng I very like this idea. I want to generate a code coverage raport to the next version and for each PR.

2023-10-13 09:49 UTC, drieseng requested changes

2023-10-13 09:49 UTC, drieseng commented on src/Renci.SshNet.Tests/Classes/Common/ExtensionsTest_Reverse.cs
> -        public void Perf_Large()
Move to benchmark project?

2023-10-13 09:50 UTC, drieseng commented
@Rob-Hague, @WojciechNagorski: I suppose we want to merge this one before we merge the PR where we move the test projects.

2023-10-13 10:06 UTC, WojciechNagorski commented
@drieseng I think it's a good idea.

2023-10-13 20:56 UTC, Rob-Hague commented on src/Renci.SshNet.Tests/Classes/Common/ExtensionsTest_Reverse.cs
> -        public void Perf_Large()
Ok, done.

2023-10-14 19:40 UTC, WojciechNagorski approved these changes

2023-10-14 19:41 UTC, merged