Enable list directory async for net framework
sshnet/SSH.NET pull request #1206
Opened 2023-10-13 15:00 UTC by Patrick-3000

The Nuget package Renci.SshNet is available for .NET Framework. However, if you call `ListDirectoryAsync` on the `SftpClient`, you will encounter a `MethodNotFoundException` only at runtime.

2023-10-13 20:01 UTC, drieseng requested changes

2023-10-13 20:01 UTC, drieseng commented on src/Renci.SshNet/SftpClient.cs
> +                    {
Please undo formatting changes.

2023-10-13 20:01 UTC, drieseng commented on src/Renci.SshNet/SftpClient.cs
> +            {
Please indent block.

2023-10-13 20:01 UTC, drieseng commented on src/Renci.SshNet/SftpClient.cs
> +                    {
Please indent block.

2023-10-13 20:01 UTC, drieseng commented on src/Renci.SshNet/Renci.SshNet.csproj
> +    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
Please make it conditional so that it only applies to TFMs that do not support **IAsyncEnumerable\<T>** out-of-the-box.

2023-10-13 21:01 UTC, Rob-Hague commented
> The Nuget package Renci.SshNet is available for .NET Framework. However, if you call `ListDirectoryAsync` on the `SftpClient`, you will encounter a `MethodNotFoundException` only at runtime.

`ListDirectoryAsync` is not included in the compilation for .NET Framework. How are you calling it?

2023-10-14 05:44 UTC, Patrick-3000 commented on src/Renci.SshNet/Renci.SshNet.csproj
> +    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
Thank you for your comment, good idea! Done.

2023-10-14 05:46 UTC, Patrick-3000 commented on src/Renci.SshNet/SftpClient.cs
> +                    {
Done.

2023-10-14 05:46 UTC, Patrick-3000 commented on src/Renci.SshNet/SftpClient.cs
> +            {
Done.

2023-10-14 05:46 UTC, Patrick-3000 commented on src/Renci.SshNet/SftpClient.cs
> +                    {
Done.

2023-10-14 14:34 UTC, drieseng approved these changes

2023-10-14 14:35 UTC, merged

2023-10-14 14:35 UTC, drieseng commented
@Patrick-3000, thanks!

2023-12-01 15:30 UTC, scott-xu commented
[SSH.NET.nuspec](https://github.com/sshnet/SSH.NET/blob/develop/build/nuget/SSH.NET.nuspec#L19) needs to be updated to add dependency Microsoft.Bcl.AsyncInterfaces 7.0.0 when target net462.
Or shall we just use [Renci.SshNet.csproj ](https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/Renci.SshNet.csproj) to build the nuget package?

2023-12-01 15:37 UTC, Rob-Hague commented
Yes, IMO we should remove nuspec and AssemblyInfo and merge them into the csproj

2023-12-02 02:24 UTC, scott-xu commented
> Yes, IMO we should remove nuspec and AssemblyInfo and merge them into the csproj

I drafted a new PR https://github.com/sshnet/SSH.NET/pull/1256

2023-12-29 14:25 UTC, WojciechNagorski commented
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1