Disable some impactful analyzers
sshnet/SSH.NET pull request #1246
Opened 2023-11-18 20:24 UTC by Rob-Hague

I promise to stop whining about analyzers if this is merged.

Before:

![image](https://github.com/sshnet/SSH.NET/assets/5132141/de9fb6a9-7ced-4add-bc61-d88756fed0c9)

After:

![image](https://github.com/sshnet/SSH.NET/assets/5132141/71a63c3c-5903-4cfc-aa51-bb0a9b42f817)

Done with a clean build each time (`git clean -xdf`). The individual numbers are quite variable, but it is around 60% build time reduction (still much longer than it used to be).

2023-11-18 20:31 UTC, WojciechNagorski commented
LGTM! I think it's good compromise.
@drieseng it's your topic? Are you agree?

2023-11-28 11:00 UTC, drieseng commented
> The individual numbers are quite variable, but it is around 60% build time reduction (still much longer than it used to be).

Is that also the explanation for the Meziantou numbers? As far as I can tell, you didn't disable any of it rules.

2023-11-28 11:03 UTC, drieseng requested changes

2023-11-28 11:03 UTC, drieseng commented on .editorconfig
> +# SA1512: Single-line comments should not be followed by a blank line
Please motivate. I'm ok with this though.

2023-11-28 11:03 UTC, drieseng commented on .editorconfig
> +dotnet_diagnostic.S4663.severity = none
I prefer to keep this one enabled.

2023-11-28 11:03 UTC, drieseng commented on .editorconfig
> +dotnet_diagnostic.S3949.severity = none
Please motivate.

2023-11-28 11:03 UTC, drieseng commented on .editorconfig
> +dotnet_diagnostic.S2053.severity = none
Please motivate.

2023-11-28 11:03 UTC, drieseng commented on .editorconfig
> -# This rule produces false errors in, for example, for loops.
Please also keep the original motivation.

2023-11-29 19:18 UTC, Rob-Hague commented
> Is that also the explanation for the Meziantou numbers? As far as I can tell, you didn't disable any of it rules.

Yes I believe so, I don't have a better explanation

(sorry, somehow I edited your comment to this comment...)

2023-12-02 13:19 UTC, drieseng approved these changes

2023-12-02 15:41 UTC, merged

2023-12-29 14:24 UTC, WojciechNagorski commented
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1