Zlib compression uses BouncyCastle as a fallback if BCL does not support
sshnet/SSH.NET pull request #1453
Opened 2024-07-21 15:57 UTC by scott-xu

…ort.

2024-07-23 10:00 UTC, WojciechNagorski requested changes
You can't run .NET Framework 4.8 test on Linux, can you?

2024-07-23 10:00 UTC, WojciechNagorski commented on appveyor.yml
> +    - dotnet build -f net48 -c Debug test/Renci.SshNet.IntegrationTests/Renci.SshNet.IntegrationTests.csproj
How do you run .NET Framework on Linux? :) You should run it on Windows.

2024-07-23 10:00 UTC, WojciechNagorski commented on appveyor.yml
> +    - sh: dotnet test -f net48 -c Debug --no-restore --no-build --results-directory artifacts --logger Appveyor --logger "console;verbosity=normal" --logger "liquid.md;LogFileName=linux_integration_t
.NET Framework 4.8 on Linux.

2024-07-23 12:27 UTC, scott-xu commented
That's a very good question. I don't know why but the CI works.

2024-07-23 12:36 UTC, scott-xu commented
It might be based on Mono.

2024-07-23 12:53 UTC, scott-xu commented
Here's CI output
```
dotnet test -f net48 -c Debug --no-restore --no-build --results-directory artifacts --logger Appveyor --logger "console;verbosity=normal" --logger "liquid.md;LogFileName=linux_integration_test_net_48_report.md" -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=../../artifacts/linux_integration_test_net_48_coverage.xml --filter Name~Zlib test/Renci.SshNet.IntegrationTests/Renci.SshNet.IntegrationTests.csproj
Test run for /home/appveyor/projects/ssh-net/test/Renci.SshNet.IntegrationTests/bin/Debug/net48/Renci.SshNet.IntegrationTests.dll (.NETFramework,Version=v4.8)
Microsoft (R) Test Execution Command Line Tool Version 17.9.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Appveyor.TestLogger: Logging to http://localhost:42353/
A total of 1 test files matched the specified pattern.
  Passed ZlibOpenSsh [596 ms]
Appveyor.TestLogger: 1 test results reported (1 enqueued).
Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 20.7936 Seconds
Saved report to: linux_integration_test_net_48_report.md
Calculating coverage result...

```

2024-07-23 13:08 UTC, WojciechNagorski commented
You're right. There is mono https://www.appveyor.com/docs/linux-images-software/

2024-07-25 10:24 UTC, WojciechNagorski approved these changes
LGTM

2024-07-25 10:24 UTC, merged