Migrate to NuGet Central Package Management
sshnet/SSH.NET pull request #1488
Opened 2024-09-08 11:01 UTC by mus65

This migrates to [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) . Versions stay the same, so there is no functional difference.

Additional changes I made as part of this:
- replaced some usages of the  `[1.0.0,)` syntax with `1.0.0` since these are equivalent, see [docs](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges)
- removed the testcontainers -> SSH.NET exclude from IntegrationTests . I can not reproduce this issue anymore. Even if it still woud be a problem, I think it would be better to use `VersionOverride` here since the version has no meaning anyway.

2024-09-10 20:50 UTC, Rob-Hague commented
Just want to double check the exclude, not sure why there would be no build warnings anymore

2024-09-11 15:59 UTC, mus65 commented
I can only reproduce the original warning with Testcontainers <= 3.5.0 which depended on SSH.NET 2020.0.2 . With Testcontainers >= 3.6.0 (which depends on SSH.NET 2023.0.0), the warning disappears.

Still no idea why this makes a difference though.

2024-09-11 16:57 UTC, drieseng requested changes

2024-09-11 16:57 UTC, drieseng commented on Directory.Packages.props
> +    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
Also set **CentralPackageVersionOverrideEnabled** to **false**. The whole idea of CPM is to manage versions centrally.

2024-09-11 16:57 UTC, drieseng commented on Directory.Packages.props
> +    <PackageVersion Include="Appveyor.TestLogger" Version="2.0.0" />
We should consider upgrading the following packages:
* BenchmarkDotNet
* Meziantou.Analyzer
* MSTest.*
* Moq
* SonarAnalyzer.CSharp

Lets do this in an another PR though.

2024-09-11 17:58 UTC, mus65 commented on Directory.Packages.props
> +    <PackageVersion Include="Appveyor.TestLogger" Version="2.0.0" />
I wll do a separate PR.

2024-09-11 18:03 UTC, drieseng approved these changes

2024-09-11 19:41 UTC, Rob-Hague approved these changes
Thanks for checking the build warnings. Let's be optimistic that it won't reoccur

2024-09-11 19:41 UTC, merged