Adding Pagant Support
sshnet/SSH.NET pull request #705
Opened 2020-07-14 22:13 UTC by kins-dev

Adds pagent support.

That said, the dependencies **requires** .Net 4.0.  Pagent support in non-windows desktop environment does not make sense, so this requirement seems reasonable.

2020-07-14 22:29 UTC, darkoperator commented
Would this support not make more sense on a Appa built with the library than on the library that provides protocol core support?

2020-07-15 01:14 UTC, kins-dev commented
Honestly I'm not sure what an Appa is in this context.

I looked at it this way,  The library handles the entire key exchange back and forth.  Since a pagent isn't getting a key but instead using side channel as a challenge response, it would require changes on the core to widen interfaces to allow that new mechanism.  This would then lead to a shim everyone who might want pagent support would need to use (add an extra layer of indirection and a possible security vector) or each application would need to do it themselves.

Rather than sending the people down the road of re-inventing the wheel, (especially since the documentation on how to do this, would basically be the same code I wrote, only in outside programs) I figured it was better to do it once, in the core.

Maybe I'm missing something here, so I'm open to other suggestions.  It would also be trivial to make this a compile time option instead, if there's a concern about performance/security.

2020-07-15 01:40 UTC, darkoperator commented
Sorry was typing a n my phone, I meant App. A better one would be OpenSSH ssh-agent since it would mean compatibility with Windows, Mac and Linux. Specially since OpenSSH is now part of Windows. Only providing my opinion as a user. Im not a project Dev :)

2020-07-15 02:13 UTC, kins-dev commented
Ah I see where you're coming from.  

Implementing the same thing in every app probably is a bad idea.  You get a bunch of copies of the example code, with stylistic or other arbitrary changes, a shim layer that gets created later that a number of people will rely on, and then a fork of the original code base.  This creates a mess and makes it very hard to push out security updates.

As for the platforms:
 - Linux: this is pretty straightforward with example code of how to read and write to a socket file.
 - Mac: this is a socket file as well, but I believe Apple's key chain is involved.  May require something special, but should be pretty easy
 - Windows:
   - Pagent: this is the putty SSH agent.  It is far and away the oldest and most widely used SSH agent.  Uses Window handles  and messages to pass challenge/response data so it works with no configuration from the user.
   - Cygwin: Uses a socket file like Linux
   - Msys: Also uses a socket file, but the format is different than cygwin
   - Native OpenSSH Windows: Uses a Windows service, the documentation is not clear if there is a socket file or if this is using a different IPC mechanism. 

Pagent solved my immediate problem and I was able to find good examples to work from.  That said I would expect in the future more ssh agent protocols to be implemented based on need.  They might even be split out to a plugin mechanism.

2020-11-23 22:01 UTC, daviburg requested changes

2020-11-23 22:01 UTC, daviburg commented on src/Renci.SshNet/PageantProtocol.cs
> +                    accessor.Write (0, IPAddress.NetworkToHostOrder (AGENT_MAX_MSGLEN - 4));
Here would a be good place to have code comments to explain what we are doing, point to documentation and/or specification that apply to this implementation.

2023-08-25 10:51 UTC, WojciechNagorski commented
I'm closing PR. This is an old issue with no votes.
@kins-dev If you still feel a change is needed, you can refresh this PR and reopen it. SSH.NET support right now .NET Standard 2.0 and .NET 7 that are cross-platform. This feature should only be usable on the relevant systems/target-framework.

2023-08-25 10:51 UTC, closed without merging