Feature: Global Response Handler (for SSH Server Keepalives)
sshnet/SSH.NET pull request #711
Opened 2020-07-29 05:12 UTC by JustinGrote

This adds a static method for responding to global requests, which simply returns a request failed packet if a global message is received. This is sufficient for the server keepalive mechanisms used by several SSH servers and is RFC4254 compliant.
https://tools.ietf.org/html/rfc4254#section-4

Resolves #709

2020-11-23 21:25 UTC, daviburg requested changes

2020-11-23 21:25 UTC, daviburg commented on src/Renci.SshNet/GlobalRequests.cs
> +            var session = (ISession) sender;
Safer if programmed as
`(sender as  ISession)?.SendMessage(new RequestFailureMessage());`

or

```
if (sender is  ISession session)
{
    session.SendMessage(new RequestFailureMessage());
}
```

2020-11-23 21:25 UTC, daviburg commented on src/Renci.SshNet/GlobalRequests.cs
> +    class GlobalRequests {
Please add a unit test for this new class and functionality.

2021-10-18 15:36 UTC, JustinGrote commented
Closing as I have no interest in pursing this further, someone else can feel free to pick it up.

2021-10-18 15:36 UTC, closed without merging