Fix avoidable exception when data length is too long
sshnet/SSH.NET pull request #823
Opened 2021-05-13 15:21 UTC by se006

Data lengths that are both longer than int.MaxValue and data bytes are now ignored and do not throw an exception.

This would come up when connecting to a Tectia SFTP server running on a mainframe.  

Credit to @edmlin for the fix.  This is for issue #713

2021-05-14 10:55 UTC, IgorMilavec requested changes
You should change/remove test Load_ShouldThrowNotSupportedExceptionWhenDataLengthIsGreaterThanInt32MaxValue for this PR to pass.

2021-05-14 13:26 UTC, se006 commented
I have removed the unit test as I cannot think of a way to enter into the middle condition, 
```
 else if (dataLength > int.MaxValue)
            {
                throw new NotSupportedException(string.Format(CultureInfo.CurrentCulture, "Data longer than {0} is not supported.", int.MaxValue));
            }
```
Perhaps this condition should be removed entirely.

2021-05-14 19:56 UTC, IgorMilavec commented
With the current implementation of SshData I believe you cannot test this case.
This exception provides a more explicit error information than the OverflowException that would happen anyway, and should stay in the code IMO.

2022-02-19 19:44 UTC, IgorMilavec commented
@se006 can you please edit the PR description (first comment) to include text "Fix #713" so this PR will be linked to the issue? Tnx!

2022-02-21 12:19 UTC, se006 commented
Fix #713 added to first comment as requested

2023-11-17 19:06 UTC, Rob-Hague approved these changes

2023-11-17 22:59 UTC, scott-xu approved these changes

2023-11-19 06:32 UTC, WojciechNagorski approved these changes
LGTM!
I wish there was a test, but I know it will be difficult.

2023-11-19 06:32 UTC, merged

2023-12-29 14:25 UTC, WojciechNagorski commented
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1